include:
 - ./common/kong/docker-compose.yaml
#  - ./common/vault/docker-compose.yaml
 - ./common/monitoring/dev/docker-compose.dev.yaml
 - ./peekup-pay/dashboard/docker-compose.yaml
 - ./peekup-pay/payment-gateway/docker-compose.yaml
 - ./peekup-pay/peekup-pay-backend/docker-compose.yaml

services:
  caddy:
    extends:
      file: common/caddy/docker-compose.yaml
      service: caddy
    volumes:
      - ./caddyfile-overrides/dev/Caddyfile.dev:/etc/caddy/Caddyfile

volumes:
  caddy_data:
  caddy_config:
