include:
#  - ./common/monitoring/docker-compose.agent.yaml
 - ./common/redis/docker-compose.yaml
 - ./common/db/docker-compose.yaml
 - ./common/kong/docker-compose.yaml
 - ./peekup-pay/peekup_pay_backend/docker-compose.yaml
services:
  caddy:
    extends:
      file: common/caddy/docker-compose.yaml
      service: caddy
    volumes:
     - ./peekup-pay:/etc/caddy/peekup-pay

volumes:
  caddy_data:
  caddy_config:
