global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
         - "10.0.5.73:9100"
         - "10.0.6.160:9100"
         - "10.0.5.156:9100"
         - "10.0.6.7:9100"
  
  - job_name: 'cadvisor'
    scrape_interval: 15s
    scheme: http
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: 
         - "10.0.5.73:8080"
         - "10.0.6.160:8080"
         - "10.0.5.156:8080"
         - "10.0.6.7:8080"

  - job_name: 'kong'
    scrape_interval: 5s
    scheme: http
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: 
         - "10.0.5.73:8001"
         - "10.0.6.160:8001"
         - "10.0.5.156:8001"
         - "10.0.6.7:8001"
