global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
         - "IP:9100"
  
  - job_name: 'cadvisor'
    scrape_interval: 15s
    scheme: http
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: 
         - "IP:8080"

  - job_name: 'kong'
    scrape_interval: 5s
    scheme: http
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: 
         - "IP:8001"
