global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
         - "10.0.5.196:9100"
         - "10.0.6.161:9100"
         - "10.0.6.114:9100"
         - "10.0.5.218:9100"
  
  - job_name: 'cadvisor'
    scrape_interval: 15s
    scheme: http
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: 
         - "10.0.5.196:8080"
         - "10.0.6.161:8080"
         - "10.0.6.114:8080"
         - "10.0.5.218:8080"

  - job_name: 'kong'
    scrape_interval: 5s
    scheme: http
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: 
         - "10.0.5.196:8001"
         - "10.0.6.161:8001"
         - "10.0.6.114:8001"
         - "10.0.5.218:8001"
