global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
         - "10.0.5.211:9100"
         - "10.0.6.174:9100"
         - "10.0.6.53:9100"
         - "10.0.5.183:9100"
  
  - job_name: 'cadvisor'
    scrape_interval: 15s
    scheme: http
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: 
         - "10.0.5.211:8080"
         - "10.0.6.174:8080"
         - "10.0.6.53:8080"
         - "10.0.5.183:8080"

  - job_name: 'kong'
    scrape_interval: 5s
    scheme: http
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: 
         - "10.0.5.211:8001"
         - "10.0.6.174:8001"
         - "10.0.6.53:8001"
         - "10.0.5.183:8001"
