global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: 
          - '10.0.12.6:9100'
          - '10.0.11.7:9100'
          - '10.0.10.5:9100'
          - '10.0.11.8:9100'
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: 
          - '10.0.12.6:8080'
          - '10.0.11.7:8080'
          - '10.0.10.5:8080'
          - '10.0.11.8:8080'
  - job_name: 'kong'
    scrape_interval: 5s
    static_configs:
      - targets: 
          - '10.0.12.6:8001'
          - '10.0.11.7:8001'
          - '10.0.10.5:8001'
          - '10.0.11.8:8001'

