services:
  peekup-pay-backend:
    build: 
      context: https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/Peek-up/peekuppay.git#${PEEKUP_PAY_BACKEND_GITHUB_BRANCH:-${DEFAULT_GITHUB_BRANCH:?DEFAULT_GITHUB_BRANCH is not set}}
    command: ./scripts/start.sh
    restart: always
    volume:
      - ../scripts/start.sh:./scripts/start.sh
    env_file:
      - ../../.env
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:?DJANGO_SECRET_KEY is not set}
      DJANGO_DEBUG: ${DJANGO_DEBUG:?DJANGO_DEBUG is not set}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:?DJANGO_ALLOWED_HOSTS is not set}
      DJANGO_CORS_ALLOW_ALL_ORIGINS: ${DJANGO_CORS_ALLOW_ALL_ORIGINS:?DJANGO_CORS_ALLOW_ALL_ORIGINS is not set}
      DJANGO_CSRF_ALLOWED_ORIGINS: ${DJANGO_CSRF_ALLOWED_ORIGINS:?DJANGO_CSRF_ALLOWED_ORIGINS is not set}
      ADMIN_EMAIL: ${ADMIN_EMAIL:?ADMIN_EMAIL is not set}
      START_CELERY_WORKER: ${START_CELERY_WORKER:-true}
      ALLOW_CRON_EXECUTION: ${ALLOW_CRON_EXECUTION:-false}

      POSTGRES_DATABASE_NAME: ${POSTGRES_DATABASE_NAME:?POSTGRES_DATABASE_NAME is not set}
      POSTGRES_DATABASE_USER: ${POSTGRES_DATABASE_USER:?POSTGRES_DATABASE_USER is not set}
      POSTGRES_DATABASE_PASSWORD: ${POSTGRES_DATABASE_PASSWORD:?POSTGRES_DATABASE_PASSWORD is not set}
      POSTGRES_DATABASE_HOST: ${POSTGRES_DATABASE_HOST:?POSTGRES_DATABASE_HOST is not set}
      POSTGRES_DATABASE_PORT: ${POSTGRES_DATABASE_PORT:?POSTGRES_DATABASE_PORT is not set}

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:?AWS_ACCESS_KEY_ID is not set}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:?AWS_SECRET_ACCESS_KEY is not set}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET:?AWS_S3_BUCKET is not set}
      AWS_REGION: ${AWS_REGION:?AWS_REGION is not set}
      FILE_UPLOAD_STORAGE: ${FILE_UPLOAD_STORAGE:?FILE_UPLOAD_STORAGE is not set}
      AWS_ENCRYPTION_SECRET_NAME: ${AWS_ENCRYPTION_SECRET_NAME:?AWS_ENCRYPTION_SECRET_NAME is not set}
      AWS_PAYLOAD_ENCRYPTION_SECRET_NAME: ${AWS_PAYLOAD_ENCRYPTION_SECRET_NAME:?AWS_PAYLOAD_ENCRYPTION_SECRET_NAME is not set}

      # PUBLISHABLE_TEST_KEY_MAGPIE: ${PUBLISHABLE_TEST_KEY_MAGPIE:?PUBLISHABLE_TEST_KEY_MAGPIE is not set}
      # SECRET_TEST_KEY_MAGPIE: ${SECRET_TEST_KEY_MAGPIE:?SECRET_TEST_KEY_MAGPIE is not set}
      PUBLISHABLE_LIVE_KEY_MAGPIE: ${PUBLISHABLE_LIVE_KEY_MAGPIE:?PUBLISHABLE_LIVE_KEY_MAGPIE is not set}
      SECRET_LIVE_KEY_MAGPIE: ${SECRET_LIVE_KEY_MAGPIE:?SECRET_LIVE_KEY_MAGPIE is not set}

      FIREBASE_SDK_KEY_PATH: ${FIREBASE_SDK_KEY_PATH:?FIREBASE_SDK_KEY_PATH is not set}

      APP_DOMAIN: ${APP_DOMAIN:?APP_DOMAIN is not set}
      PWA_DOMAIN: ${PWA_DOMAIN:?PWA_DOMAIN is not set}
      WALLET_PWA_SUCCESS_URL: ${WALLET_PWA_SUCCESS_URL:?WALLET_PWA_SUCCESS_URL is not set}
      WALLET_PWA_FAILURE_URL: ${WALLET_PWA_FAILURE_URL:?WALLET_PWA_FAILURE_URL is not set}
      DOCS_URL: ${DOCS_URL:?DOCS_URL is not set}

      MY_BUSYBEE_SENDER_ID: ${MY_BUSYBEE_SENDER_ID:?MY_BUSYBEE_SENDER_ID is not set}
      MY_BUSYBEE_API_KEY: ${MY_BUSYBEE_API_KEY:?MY_BUSYBEE_API_KEY is not set}
      MY_BUSYBEE_CLIENT_ID: ${MY_BUSYBEE_CLIENT_ID:?MY_BUSYBEE_CLIENT_ID is not set}
      MY_BUSYBEE_API_ENDPOINT: ${MY_BUSYBEE_API_ENDPOINT:?MY_BUSYBEE_API_ENDPOINT is not set}

      MAGPIE_PAY_DOMAIN: ${MAGPIE_PAY_DOMAIN:?MAGPIE_PAY_DOMAIN is not set}
      MAGPIE_API_DOMAIN: ${MAGPIE_API_DOMAIN:?MAGPIE_API_DOMAIN is not set}
      CHECKOUT_SESSION_URL: ${CHECKOUT_SESSION_URL:?CHECKOUT_SESSION_URL is not set}
      REFUND_CHARGE_URL: ${REFUND_CHARGE_URL:?REFUND_CHARGE_URL is not set}

      BRANKAS_API_KEY: ${BRANKAS_API_KEY:?BRANKAS_API_KEY is not set}
      BRANKAS_API_DOMAIN: ${BRANKAS_API_DOMAIN:?BRANKAS_API_DOMAIN is not set}
      PEEKUPPAY_BRANKAS_BANK_ACCOUNT_ID: ${PEEKUPPAY_BRANKAS_BANK_ACCOUNT_ID:?PEEKUPPAY_BRANKAS_BANK_ACCOUNT_ID is not set}
      # BRANKAS_IP_ADDRESS: ${BRANKAS_IP_ADDRESS:?BRANKAS_IP_ADDRESS is not set}

      MQTT_BROKER_NEW: ${MQTT_BROKER_NEW:?MQTT_BROKER_NEW is not set}
      MQTT_PORT: ${MQTT_PORT:?MQTT_PORT is not set}
      MQTT_USERNAME: ${MQTT_USERNAME:?MQTT_USERNAME is not set}
      MQTT_PASSWORD: ${MQTT_PASSWORD:?MQTT_PASSWORD is not set}

      ENCRYPT_KEY: ${ENCRYPT_KEY:?ENCRYPT_KEY is not set}
      PAYLOAD_ENCRYPTION_KEY: ${PAYLOAD_ENCRYPTION_KEY:?PAYLOAD_ENCRYPTION_KEY is not set}

      MAGPIE_FEES: ${MAGPIE_FEES:?MAGPIE_FEES is not set}
      BRANKAS_FEES: ${BRANKAS_FEES:?BRANKAS_FEES is not set}

      PAYMONGO_API_DOMAIN: ${PAYMONGO_API_DOMAIN:?PAYMONGO_API_DOMAIN is not set}
      SECRET_TEST_KEY_PAYMONGO: ${SECRET_TEST_KEY_PAYMONGO:?SECRET_TEST_KEY_PAYMONGO is not set}

      XENDIT_API_DOMAIN: ${XENDIT_API_DOMAIN:?XENDIT_API_DOMAIN is not set}
      XENDIT_API_SECRET_KEY: ${XENDIT_API_SECRET_KEY:?XENDIT_API_SECRET_KEY is not set}
      XENDIT_WEBHOOK_VERIFICATION_TOKEN: ${XENDIT_WEBHOOK_VERIFICATION_TOKEN:?XENDIT_WEBHOOK_VERIFICATION_TOKEN is not set}
      MERCHANT_CRM_DOMAIN: ${MERCHANT_CRM_DOMAIN:?MERCHANT_CRM_DOMAIN is not set}

      OZONE_BASIC_TOKEN: ${OZONE_BASIC_TOKEN:?OZONE_BASIC_TOKEN is not set}
      TOKEN_ENDPOINT: ${TOKEN_ENDPOINT:?TOKEN_ENDPOINT is not set}
      OZONE_CERT_PATH: ${OZONE_CERT_PATH:?OZONE_CERT_PATH is not set}
      OZONE_KEY_PATH: ${OZONE_KEY_PATH:?OZONE_KEY_PATH is not set}
      OB_PARTICIPANT_ID: ${OB_PARTICIPANT_ID:?OB_PARTICIPANT_ID is not set}
      OZONE_RS_DOMAIN: ${OZONE_RS_DOMAIN:?OZONE_RS_DOMAIN is not set}
      BANK_SORT_CODE: ${BANK_SORT_CODE:?BANK_SORT_CODE is not set}
      PEEKUPPAY_SORT_CODE_ACCOUNT_NUMBER: ${PEEKUPPAY_SORT_CODE_ACCOUNT_NUMBER:?PEEKUPPAY_SORT_CODE_ACCOUNT_NUMBER is not set}
      PEEKUPPAY_ACCOUNT_NAME: ${PEEKUPPAY_ACCOUNT_NAME:?PEEKUPPAY_ACCOUNT_NAME is not set}
      OZONE_REDIRECT_URI: ${OZONE_REDIRECT_URI:?OZONE_REDIRECT_URI is not set}

      NETBANK_API_DOMAIN: ${NETBANK_API_DOMAIN:?NETBANK_API_DOMAIN is not set}
      NETBANK_ENVIRONMENT_ACCESS_CLIENT_ID: ${NETBANK_ENVIRONMENT_ACCESS_CLIENT_ID:?NETBANK_ENVIRONMENT_ACCESS_CLIENT_ID is not set}
      NETBANK_ENVIRONMENT_ACCESS_CLIENT_SECRET: ${NETBANK_ENVIRONMENT_ACCESS_CLIENT_SECRET:?NETBANK_ENVIRONMENT_ACCESS_CLIENT_SECRET is not set}
      NETBANK_AUTHENTICATION_CODE_CLIENT_ID: ${NETBANK_AUTHENTICATION_CODE_CLIENT_ID:?NETBANK_AUTHENTICATION_CODE_CLIENT_ID is not set}
      NETBANK_AUTHENTICATION_CODE_CLIENT_SECRET: ${NETBANK_AUTHENTICATION_CODE_CLIENT_SECRET:?NETBANK_AUTHENTICATION_CODE_CLIENT_SECRET is not set}
      NETBANK_BANK_CODE: ${NETBANK_BANK_CODE:?NETBANK_BANK_CODE is not set}
      NETBANK_IP_ADDRESS: ${NETBANK_IP_ADDRESS:?NETBANK_IP_ADDRESS is not set}

      PEEKUPPAY_NETBANK_CUSTOMER_ID: ${PEEKUPPAY_NETBANK_CUSTOMER_ID:?PEEKUPPAY_NETBANK_CUSTOMER_ID is not set}
      PEEKUPPAY_NETBANK_ACCOUNT_NUMBER: ${PEEKUPPAY_NETBANK_ACCOUNT_NUMBER:?PEEKUPPAY_NETBANK_ACCOUNT_NUMBER is not set}

      PEEKUPPAY_ADDRESS_LINE1: ${PEEKUPPAY_ADDRESS_LINE1:?PEEKUPPAY_ADDRESS_LINE1 is not set}
      PEEKUPPAY_ADDRESS_LINE2: ${PEEKUPPAY_ADDRESS_LINE2:?PEEKUPPAY_ADDRESS_LINE2 is not set}
      PEEKUPPAY_CITY: ${PEEKUPPAY_CITY:?PEEKUPPAY_CITY is not set}
      PEEKUPPAY_PROVINCE: ${PEEKUPPAY_PROVINCE:?PEEKUPPAY_PROVINCE is not set}
      PEEKUPPAY_REGION: ${PEEKUPPAY_REGION:?PEEKUPPAY_REGION is not set}
      PEEKUPPAY_ZIP_CODE: ${PEEKUPPAY_ZIP_CODE:?PEEKUPPAY_ZIP_CODE is not set}

      GATEWAY_PROVIDER: ${GATEWAY_PROVIDER:?GATEWAY_PROVIDER is not set}
      DISBURSEMENT_PROVIDER: ${DISBURSEMENT_PROVIDER:?DISBURSEMENT_PROVIDER is not set}
      WALLET_PROVIDER: ${WALLET_PROVIDER:?WALLET_PROVIDER is not set}
      CASHIN_PROVIDER: ${CASHIN_PROVIDER:?CASHIN_PROVIDER is not set}
      CASHOUT_PROVIDER: ${CASHOUT_PROVIDER:?CASHOUT_PROVIDER is not set}
      WALLET_CASHIN_PROVIDER: ${WALLET_CASHIN_PROVIDER:?WALLET_CASHIN_PROVIDER is not set}
      WALLET_CASHOUT_PROVIDER: ${WALLET_CASHOUT_PROVIDER:?WALLET_CASHOUT_PROVIDER is not set}

      ENVIRONMENT: ${ENVIRONMENT:?ENVIRONMENT is not set}
      OTP_WHITELISTED_PHONE_NUMBERS: ${OTP_WHITELISTED_PHONE_NUMBERS:?OTP_WHITELISTED_PHONE_NUMBERS is not set}
      OTP_WHITELISTED_EMAILS: ${OTP_WHITELISTED_EMAILS:?OTP_WHITELISTED_EMAILS is not set}

      CELERY_REDIS_BROKER_URL: ${CELERY_REDIS_BROKER_URL:?CELERY_REDIS_BROKER_URL is not set}
      RUN_CELERY_SYNCHRONOUSLY: ${RUN_CELERY_SYNCHRONOUSLY:?RUN_CELERY_SYNCHRONOUSLY is not set}
      ENCRYPT_PAYLOAD: ${ENCRYPT_PAYLOAD:?ENCRYPT_PAYLOAD is not set}

      REDIS_SSL_CONNECTION: ${REDIS_SSL_CONNECTION:?REDIS_SSL_CONNECTION is not set}
      REDIS_CONNECTION_URL: ${REDIS_CONNECTION_URL:?REDIS_CONNECTION_URL is not set}
      REDIS_HOST: ${REDIS_HOST:?REDIS_HOST is not set}
      REDIS_PORT: ${REDIS_PORT:?REDIS_PORT is not set}
      REDIS_USERNAME: ${REDIS_USERNAME:?REDIS_USERNAME is not set}
      # REDIS_PASSWORD: ${REDIS_PASSWORD:?REDIS_PASSWORD is not set}

      HYPERVERGE_APP_ID: ${HYPERVERGE_APP_ID:?HYPERVERGE_APP_ID is not set}
      HYPERVERGE_APP_KEY: ${HYPERVERGE_APP_KEY:?HYPERVERGE_APP_KEY is not set}
      HYPERVERGE_WORKFLOW_ID: ${HYPERVERGE_WORKFLOW_ID:?HYPERVERGE_WORKFLOW_ID is not set}
      HYPERVERGE_DRIVER_WORKFLOW_ID: ${HYPERVERGE_DRIVER_WORKFLOW_ID:?HYPERVERGE_DRIVER_WORKFLOW_ID is not set}
      HYPERVERGE_ID_CARD_MODULE_ID: ${HYPERVERGE_ID_CARD_MODULE_ID:?HYPERVERGE_ID_CARD_MODULE_ID is not set}
      HYPERVERGE_SIGNATURE_MODULE_ID: ${HYPERVERGE_SIGNATURE_MODULE_ID:?HYPERVERGE_SIGNATURE_MODULE_ID is not set}
      HYPERVERGE_LIVENESS_MODULE_ID: ${HYPERVERGE_LIVENESS_MODULE_ID:?HYPERVERGE_LIVENESS_MODULE_ID is not set}
      
      COINS_PH_BASE_URL: ${COINS_PH_BASE_URL:?COINS_PH_BASE_URL is not set}
      COINS_PH_WEBHOOK_SECRET: ${COINS_PH_WEBHOOK_SECRET:?COINS_PH_WEBHOOK_SECRET is not set}
      #COINS_PH_PRIVATE_KEY: ${COINS_PH_PRIVATE_KEY:?COINS_PH_PRIVATE_KEY is not set}
      COINS_PH_API_KEY: ${COINS_PH_API_KEY:?HYPERVERGE_LIVCOINS_PH_API_KEYENESS_MODULE_ID is not set}
      COINS_PH_API_SECRET: ${COINS_PH_API_SECRET:?COINS_PH_API_SECRET is not set}
