services:
  payment-gateway:
    build:
      context: https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/Peek-up/peekuppay-pwa-gateway.git#${PEEKUP_PAY_BACKEND_GITHUB_BRANCH:-${DEFAULT_GITHUB_BRANCH:?DEFAULT_GITHUB_BRANCH is not set}}
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_DOMAIN: ${NEXT_PUBLIC_API_DOMAIN:?NEXT_PUBLIC_API_DOMAIN is not set}
        NEXT_PUBLIC_AI_API_DOMAIN: ${NEXT_PUBLIC_AI_API_DOMAIN:?NEXT_PUBLIC_AI_API_DOMAIN is not set}
        NEXT_PUBLIC_AUTH_TOKEN: ${NEXT_PUBLIC_AUTH_TOKEN:?NEXT_PUBLIC_AUTH_TOKEN is not set}
        NEXT_PUBLIC_AES_KEY: ${NEXT_PUBLIC_AES_KEY:?NEXT_PUBLIC_AES_KEY is not set}
        NEXT_PUBLIC_AWS_ACCESS_KEY_ID: ${NEXT_PUBLIC_AWS_ACCESS_KEY_ID:?NEXT_PUBLIC_AWS_ACCESS_KEY_ID is not set}
        NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY: ${NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY:?NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY is not set}
        NEXT_PUBLIC_AWS_REGION: ${NEXT_PUBLIC_AWS_REGION:?NEXT_PUBLIC_AWS_REGION is not set}
        NEXT_PUBLIC_AWS_PAYLOAD_ENCRYPTION_SECRET_NAME: ${NEXT_PUBLIC_AWS_PAYLOAD_ENCRYPTION_SECRET_NAME:?NEXT_PUBLIC_AWS_PAYLOAD_ENCRYPTION_SECRET_NAME is not set}
        NEXT_PUBLIC_ENCRYPT_PAYLOAD: ${NEXT_PUBLIC_ENCRYPT_PAYLOAD:?NEXT_PUBLIC_ENCRYPT_PAYLOAD is not set}
    restart: always
    env_file:
      - .env