include:
 - ./common/monitoring/uat/docker-compose.uat-stateful.yaml
services:
  caddy:
    extends:
      file: common/caddy/docker-compose.yaml
      service: caddy
    volumes:
      - ./caddyfile-overrides/uat/Caddyfile.uat:/etc/caddy/Caddyfile

volumes:
  caddy_data:
  caddy_config:
