services:
  db:
    image: postgres:17.2
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_DATABASE_USER:?POSTGRES_DATABASE_USER is not set}
      POSTGRES_PASSWORD: ${POSTGRES_DATABASE_PASSWORD:?POSTGRES_DATABASE_PASSWORD is not set}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME:?POSTGRES_DATABASE_NAME is not set}
volumes:
  db: